$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: >-
  python train.py --training_data ${{inputs.training_data}} --reg_rate ${{inputs.reg_rate}} --subscription_id ${{inputs.subscription_id}} --resource_group ${{inputs.resource_group}} --workspace ${{inputs.workspace}} --env ${{inputs.env}} --run_id ${{inputs.run_id}}
inputs:
  training_data: 
    type: uri_folder 
    path: azureml:diabetes-dev-folder:1 
  reg_rate: 0.01
  subscription_id: 5660f606-b840-4a8d-9e4f-c058b09a34a2
  resource_group: srmds-dev-rg
  workspace: srmds-dev-ws
  env: dev
  run_id: %RUN_ID%
environment: azureml:Custom@latest
compute: srmds-dev-cc
display_name:  diabetes-model-dev
experiment_name: diabetes-training-dev
description: DEV - Train job for diabetes