name: Trigger an Azure Machine Learning job
on:
  push:
    branches:
      - main
  workflow_dispatch:  # enables manual triggering of workflow from actions tab on github
    inputs:
      resource_group:
        description: 'resource group'     
        required: true
        default: srmds-dev-rg 
      workspace_name:
        description: 'workspace name'
        required: true
        default: srmds-dev-ws
jobs:
  train-dev:
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd src
    - name: run pipeline dev
      # run: az ml job create --file src/job.yml --resource-group ${{ github.event.inputs.resource_group }} --workspace-name ${{ github.event.inputs.workspace_name }}
      # --stream will result in streaming the job logs and results waiting for the job completion before the next job may be started (it must succeed in order to trigger next job otherwise the workflow will exit): https://learn.microsoft.com/en-us/cli/azure/ml/job?view=azure-cli-latest#az-ml-job-stream
      run: |
        run_id=${{ github.run_id }}
        sed -i 's/%RUN_ID%/$run_id/g' src/train-job-dev.yml
        cat src/train-job-dev.yml
        az ml job create --file src/train-job-dev.yml --resource-group srmds-dev-rg --workspace-name srmds-dev-ws --stream
  train-prd:
    environment:
      name: prd
    needs: train-dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd src
    - name: run pipeline prd
      # run: az ml job create --file src/job.yml --resource-group ${{ github.event.inputs.resource_group }} --workspace-name ${{ github.event.inputs.workspace_name }}
      run: |
        run_id=${{ github.run_id }}
        sed -i 's/%RUN_ID%/$run_id/g' src/train-job-prd.yml
        cat src/train-job-prd.yml
        az ml job create --name diabetes-model-prd-${{ github.run_id }} --file src/train-job-prd.yml --resource-group srmds-dev-rg --workspace-name srmds-dev-ws --stream