name: Trigger an Azure Machine Learning job
on:
  push:
    branches:
      - main
  workflow_dispatch:  # enables manual triggering of workflow from actions tab on github
    inputs:
      resource_group:
        description: 'resource group'     
        required: true
        default: srmds-dev-rg 
      workspace_name:
        description: 'workspace name'
        required: true
        default: srmds-dev-ws
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd src
    - name: run pipeline
      # run: az ml job create --file src/job.yml --resource-group ${{ github.event.inputs.resource_group }} --workspace-name ${{ github.event.inputs.workspace_name }}
      run: az ml job create --file src/job.yml --resource-group srmds-dev-rg --workspace-name srmds-dev-ws

      